  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=mypython
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=kid_1412
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
